-- MySQL Script generated by MySQL Workbench
-- ma 26 jun 2017 18:48:31 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbi334307
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbi334307
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbi334307` DEFAULT CHARACTER SET utf8 ;
USE `dbi334307` ;

-- -----------------------------------------------------
-- Table `dbi334307`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbi334307`.`customer` ;

CREATE TABLE IF NOT EXISTS `dbi334307`.`customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(65) NULL,
  `phone` VARCHAR(20) NULL,
  PRIMARY KEY (`customer_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbi334307`.`inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbi334307`.`inventory` ;

CREATE TABLE IF NOT EXISTS `dbi334307`.`inventory` (
  `part_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`part_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbi334307`.`car_model`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbi334307`.`car_model` ;

CREATE TABLE IF NOT EXISTS `dbi334307`.`car_model` (
  `model_id` INT NOT NULL AUTO_INCREMENT,
  `accumulator_id` INT NULL,
  `tires_id` INT NULL,
  `rims_id` INT NULL,
  `interior_id` INT NULL,
  `engine_id` INT NULL,
  `suspension_id` INT NULL,
  `transmission_id` INT NULL,
  `chassis_id` INT NULL,
  `extra_id` VARCHAR(65) NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`model_id`),
  INDEX `FK_accumulatorId_idx` (`accumulator_id` ASC),
  INDEX `FK_tiresId_idx` (`tires_id` ASC),
  INDEX `FK_rimsId_idx` (`rims_id` ASC),
  INDEX `FK_interiorId_idx` (`interior_id` ASC),
  INDEX `FK_engineId_idx` (`engine_id` ASC),
  INDEX `FK_suspensionId_idx` (`suspension_id` ASC),
  INDEX `FK_transmissionId_idx` (`transmission_id` ASC),
  INDEX `FK_chassisId_idx` (`chassis_id` ASC),
  CONSTRAINT `FK_accumulatorId`
    FOREIGN KEY (`accumulator_id`)
    REFERENCES `dbi334307`.`inventory` (`part_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_tiresId`
    FOREIGN KEY (`tires_id`)
    REFERENCES `dbi334307`.`inventory` (`part_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_rimsId`
    FOREIGN KEY (`rims_id`)
    REFERENCES `dbi334307`.`inventory` (`part_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_interiorId`
    FOREIGN KEY (`interior_id`)
    REFERENCES `dbi334307`.`inventory` (`part_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_engineId`
    FOREIGN KEY (`engine_id`)
    REFERENCES `dbi334307`.`inventory` (`part_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_suspensionId`
    FOREIGN KEY (`suspension_id`)
    REFERENCES `dbi334307`.`inventory` (`part_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_transmissionId`
    FOREIGN KEY (`transmission_id`)
    REFERENCES `dbi334307`.`inventory` (`part_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_chassisId`
    FOREIGN KEY (`chassis_id`)
    REFERENCES `dbi334307`.`inventory` (`part_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbi334307`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbi334307`.`order` ;

CREATE TABLE IF NOT EXISTS `dbi334307`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `model_id` INT NULL,
  `customer_id` INT NULL,
  `issued_date` DATETIME NULL,
  `expected_date` DATETIME NULL,
  `processed_date` DATETIME NULL,
  `priority` VARCHAR(45) NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_model_id_idx` (`model_id` ASC),
  INDEX `fk_customer_id_idx` (`customer_id` ASC),
  CONSTRAINT `fk_model_id`
    FOREIGN KEY (`model_id`)
    REFERENCES `dbi334307`.`car_model` (`model_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `dbi334307`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbi334307`.`processed_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbi334307`.`processed_order` ;

CREATE TABLE IF NOT EXISTS `dbi334307`.`processed_order` (
  `order_id` INT NOT NULL,
  `model_id` INT NULL,
  `customer_id` INT NULL,
  `issued_date` DATETIME NULL,
  `expected_date` DATETIME NULL,
  `processed_date` DATETIME NULL,
  `priority` VARCHAR(45) NULL,
  PRIMARY KEY (`order_id`),
  INDEX `FK_model_id_idx` (`model_id` ASC),
  INDEX `FK_customer_id_idx` (`customer_id` ASC),
  CONSTRAINT `FK_m_id`
    FOREIGN KEY (`model_id`)
    REFERENCES `dbi334307`.`car_model` (`model_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_c_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `dbi334307`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
